### ISSUE TITLE
Power transitor issues (Q1)

### ISSUE THREAD

**Issue by saper-2** [maitesam/Reflow_Hotplate#1]
I have basically 2 things to point out aroung Q1:

1. DMG1012T is in SOT-523 footprint, not in SOT-223 , 👉  fix P/N in schematic.
2. SOT-223 pin 4 "tab" should be connected to GND too, and around there should be some via for thermal dissipation to both GND zones.

**Comment by aitesam961** [comment]
Eagle Eye Spotting.
Will work on fixing it soon.

**Comment by aitesam961** [comment]
Invalid

**Comment by Triton2020** [comment]
Hi, what is the Stand for this Fix ? I see no change on the PCB layout, what means your respond on thios Problem "Invalid" ???????

**Comment by aitesam961** [comment]
Hi, The case is verified and it is not an issue. Please check the source files.
Thanks

**Comment by Triton2020** [comment]
It is not realy a Hint "check Source File" please can you explain what is the point ????

**Comment by arrowsmashing** [comment]
Is there a recomended replacement part for Q1, have a DMG1012T-7, but it is too small to fit the pads?
