### ISSUE TITLE
Thermal relief on pads connected to zone

### ISSUE THREAD

**Issue by saper-2** [maitesam/Reflow_Hotplate#2]
Hi,

You don't have thermal relief on pads that connect to GND zone(s). It make much harder to solder parts, especially when it's not needed in 99,9% of them to have direct-connect style. Only in Q1 it desirable to use direct-connect style. In others parts not really. For small part 10-20mils wide, and 10mils margin from pad is fine. For e.g. components "bigger" like electrolytic capacitors or power jack 20-30mils width (10mils spacing too) should be fine in this circuit.

**Comment by aitesam961** [comment]
Invalid
