### ISSUE TITLE
Other suggestions

### ISSUE THREAD

**Issue by saper-2** [maitesam/Reflow_Hotplate#3]
And few other suggestions 😄 

1. When drawing slots for milling it's easier for fab just by drawing a line (track) on mechanical layer (that have width of mill bit diameter (mostly common bit sizes used by fab house have: 2mm and 3mm ) , so there is no need for wasting time to draw outline 😉 .
I use some User..... layer for this, and also I draw one in margin-layer (edge.cuts). Of course I leave note for fab house that on this layer is mill drawing.
2. U3 is a bit in unfortunate place 😉 , it's not directly on hot-plate section , and it "cooled down" by GND zones... since you're have milling already maybe think about something to make it "separable" in case if someone decide to brake apart board into control and hot-plate part. maybe mill a bit around it (using 2mm bit?) so more heat transfer from hot-plate part, and will be cooled less by control-circuit-part
3. Have you considered creating hot-plate using MCPCB (pcb aluminum , like the one used in power-led modules as radiator 😄 ). And I see JLC have rather acceptable price for it too.

**Comment by aitesam961** [comment]
Invalid
