### ISSUE TITLE
Arduino IDE

### ISSUE THREAD

**Issue by arrowsmashing** [maitesam/Reflow_Hotplate#4]
Could you give some hints on the settings to use in Arduino IDE to upload the arduino.h to the PIC? E.g. what board to use in the settings?

**Comment by aitesam961** [comment]
You can follow this guide on Instructables
https://www.instructables.com/how-to-program-a-PIC-18F2550-or-18f4550-with-Ardui/
BTW, I'd like to inform that I have noticed minor issues with hardware design of this project recently.  I cannot promise immediate solution but I will redesign this project once I get out of my extremely busy work routine.
